name: tiket_wisata
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0
  image_picker: ^1.0.7  
  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0

dev_dependencies:
  build_runner: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
